/*
Navicat MySQL Data Transfer

Source Server         : 01
Source Server Version : 80024
Source Host           : localhost:3306
Source Database       : mysql

Target Server Type    : MYSQL
Target Server Version : 80024
File Encoding         : 65001

Date: 2021-06-07 17:51:38
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `securities`
-- ----------------------------
DROP TABLE IF EXISTS `securities`;
CREATE TABLE `securities` (
  `index` bigint DEFAULT NULL,
  `Ticker symbol` text,
  `Security` text,
  `SEC filings` text,
  `GICS Sector` text,
  `GICS Sub Industry` text,
  `Address of Headquarters` text,
  `Date first added` text,
  `CIK` bigint DEFAULT NULL,
  KEY `ix_securities_index` (`index`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Records of securities
-- ----------------------------
INSERT INTO `securities` VALUES ('0', 'MMM', '3M Company', 'reports', 'Industrials', 'Industrial Conglomerates', 'St. Paul, Minnesota', null, '66740');
INSERT INTO `securities` VALUES ('1', 'ABT', 'Abbott Laboratories', 'reports', 'Health Care', 'Health Care Equipment', 'North Chicago, Illinois', '1964-03-31', '1800');
INSERT INTO `securities` VALUES ('2', 'ABBV', 'AbbVie', 'reports', 'Health Care', 'Pharmaceuticals', 'North Chicago, Illinois', '2012-12-31', '1551152');
INSERT INTO `securities` VALUES ('3', 'ACN', 'Accenture plc', 'reports', 'Information Technology', 'IT Consulting & Other Services', 'Dublin, Ireland', '2011-07-06', '1467373');
INSERT INTO `securities` VALUES ('4', 'ATVI', 'Activision Blizzard', 'reports', 'Information Technology', 'Home Entertainment Software', 'Santa Monica, California', '2015-08-31', '718877');
INSERT INTO `securities` VALUES ('5', 'AYI', 'Acuity Brands Inc', 'reports', 'Industrials', 'Electrical Components & Equipment', 'Atlanta, Georgia', '2016-05-03', '1144215');
INSERT INTO `securities` VALUES ('6', 'ADBE', 'Adobe Systems Inc', 'reports', 'Information Technology', 'Application Software', 'San Jose, California', '1997-05-05', '796343');
INSERT INTO `securities` VALUES ('7', 'AAP', 'Advance Auto Parts', 'reports', 'Consumer Discretionary', 'Automotive Retail', 'Roanoke, Virginia', '2015-07-09', '1158449');
INSERT INTO `securities` VALUES ('8', 'AES', 'AES Corp', 'reports', 'Utilities', 'Independent Power Producers & Energy Traders', 'Arlington, Virginia', null, '874761');
INSERT INTO `securities` VALUES ('9', 'AET', 'Aetna Inc', 'reports', 'Health Care', 'Managed Health Care', 'Hartford, Connecticut', '1976-06-30', '1122304');
INSERT INTO `securities` VALUES ('10', 'AMG', 'Affiliated Managers Group Inc', 'reports', 'Financials', 'Asset Management & Custody Banks', 'Beverly, Massachusetts', '2014-07-01', '1004434');
INSERT INTO `securities` VALUES ('11', 'AFL', 'AFLAC Inc', 'reports', 'Financials', 'Life & Health Insurance', 'Columbus, Georgia', null, '4977');
INSERT INTO `securities` VALUES ('12', 'A', 'Agilent Technologies Inc', 'reports', 'Health Care', 'Health Care Equipment', 'Santa Clara, California', null, '1090872');
INSERT INTO `securities` VALUES ('13', 'APD', 'Air Products & Chemicals Inc', 'reports', 'Materials', 'Industrial Gases', 'Allentown, Pennsylvania', '1985-04-30', '2969');
INSERT INTO `securities` VALUES ('14', 'AKAM', 'Akamai Technologies Inc', 'reports', 'Information Technology', 'Internet Software & Services', 'Cambridge, Massachusetts', '2007-07-12', '1086222');
INSERT INTO `securities` VALUES ('15', 'ALK', 'Alaska Air Group Inc', 'reports', 'Industrials', 'Airlines', 'Seattle, Washington', '2016-05-13', '766421');
INSERT INTO `securities` VALUES ('16', 'ALB', 'Albemarle Corp', 'reports', 'Materials', 'Specialty Chemicals', 'Baton Rouge, Louisiana', '2016-07-01', '915913');
INSERT INTO `securities` VALUES ('17', 'ALXN', 'Alexion Pharmaceuticals', 'reports', 'Health Care', 'Biotechnology', 'Cheshire, Connecticut', '2012-05-25', '899866');
INSERT INTO `securities` VALUES ('18', 'ALLE', 'Allegion', 'reports', 'Industrials', 'Building Products', 'Dublin, Ireland', '2013-12-02', '1579241');
INSERT INTO `securities` VALUES ('19', 'AGN', 'Allergan, Plc', 'reports', 'Health Care', 'Pharmaceuticals', 'Dublin, Ireland', null, '884629');
INSERT INTO `securities` VALUES ('20', 'ADS', 'Alliance Data Systems', 'reports', 'Information Technology', 'Data Processing & Outsourced Services', 'Plano, Texas', '2013-12-23', '1101215');
INSERT INTO `securities` VALUES ('21', 'LNT', 'Alliant Energy Corp', 'reports', 'Utilities', 'Electric Utilities', 'Madison, Wisconsin', '2016-07-01', '352541');
INSERT INTO `securities` VALUES ('22', 'ALL', 'Allstate Corp', 'reports', 'Financials', 'Property & Casualty Insurance', 'Northfield Township, Illinois', null, '899051');
INSERT INTO `securities` VALUES ('23', 'GOOGL', 'Alphabet Inc Class A', 'reports', 'Information Technology', 'Internet Software & Services', 'Mountain View, California', '2014-04-03', '1652044');
INSERT INTO `securities` VALUES ('24', 'GOOG', 'Alphabet Inc Class C', 'reports', 'Information Technology', 'Internet Software & Services', 'Mountain View, California', null, '1652044');
INSERT INTO `securities` VALUES ('25', 'MO', 'Altria Group Inc', 'reports', 'Consumer Staples', 'Tobacco', 'Richmond, Virginia', null, '764180');
INSERT INTO `securities` VALUES ('26', 'AMZN', 'Amazon.com Inc', 'reports', 'Consumer Discretionary', 'Internet & Direct Marketing Retail', 'Seattle, Washington', '2005-11-18', '1018724');
INSERT INTO `securities` VALUES ('27', 'AEE', 'Ameren Corp', 'reports', 'Utilities', 'MultiUtilities', 'St. Louis, Missouri', '1991-09-19', '1002910');
INSERT INTO `securities` VALUES ('28', 'AAL', 'American Airlines Group', 'reports', 'Industrials', 'Airlines', 'Fort Worth, Texas', '2015-03-23', '6201');
INSERT INTO `securities` VALUES ('29', 'AEP', 'American Electric Power', 'reports', 'Utilities', 'Electric Utilities', 'Columbus, Ohio', null, '4904');
INSERT INTO `securities` VALUES ('30', 'AXP', 'American Express Co', 'reports', 'Financials', 'Consumer Finance', 'New York, New York', '1976-06-30', '4962');
INSERT INTO `securities` VALUES ('31', 'AIG', 'American International Group, Inc.', 'reports', 'Financials', 'Property & Casualty Insurance', 'New York, New York', '1980-03-31', '5272');
INSERT INTO `securities` VALUES ('32', 'AMT', 'American Tower Corp A', 'reports', 'Real Estate', 'Specialized REITs', 'Boston, Massachusetts', '2007-11-19', '1053507');
INSERT INTO `securities` VALUES ('33', 'AWK', 'American Water Works Company Inc', 'reports', 'Utilities', 'Water Utilities', 'Voorhees, New Jersey', '2016-03-04', '1410636');
INSERT INTO `securities` VALUES ('34', 'AMP', 'Ameriprise Financial', 'reports', 'Financials', 'Asset Management & Custody Banks', 'Minneapolis, Minnesota', null, '820027');
INSERT INTO `securities` VALUES ('35', 'ABC', 'AmerisourceBergen Corp', 'reports', 'Health Care', 'Health Care Distributors', 'Chesterbrook, Pennsylvania', null, '1140859');
INSERT INTO `securities` VALUES ('36', 'AME', 'AMETEK Inc', 'reports', 'Industrials', 'Electrical Components & Equipment', 'Berwyn, Pennsylvania', '2013-09-23', '1037868');
INSERT INTO `securities` VALUES ('37', 'AMGN', 'Amgen Inc', 'reports', 'Health Care', 'Biotechnology', 'Thousand Oaks, California', '1992-01-02', '318154');
INSERT INTO `securities` VALUES ('38', 'APH', 'Amphenol Corp', 'reports', 'Information Technology', 'Electronic Components', 'Wallingford, Connecticut', '2008-09-30', '820313');
INSERT INTO `securities` VALUES ('39', 'APC', 'Anadarko Petroleum Corp', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'The Woodlands, Texas', null, '773910');
INSERT INTO `securities` VALUES ('40', 'ADI', 'Analog Devices, Inc.', 'reports', 'Information Technology', 'Semiconductors', 'Norwood, Massachusetts', null, '6281');
INSERT INTO `securities` VALUES ('41', 'ANTM', 'Anthem Inc.', 'reports', 'Health Care', 'Managed Health Care', 'Indianapolis, Indiana', null, '1156039');
INSERT INTO `securities` VALUES ('42', 'AON', 'Aon plc', 'reports', 'Financials', 'Insurance Brokers', 'London, United Kingdom', null, '315293');
INSERT INTO `securities` VALUES ('43', 'APA', 'Apache Corporation', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', null, '6769');
INSERT INTO `securities` VALUES ('44', 'AIV', 'Apartment Investment & Mgmt', 'reports', 'Real Estate', 'REITs', 'Denver, Colorado', null, '922864');
INSERT INTO `securities` VALUES ('45', 'AAPL', 'Apple Inc.', 'reports', 'Information Technology', 'Computer Hardware', 'Cupertino, California', '1982-11-30', '320193');
INSERT INTO `securities` VALUES ('46', 'AMAT', 'Applied Materials Inc', 'reports', 'Information Technology', 'Semiconductor Equipment', 'Santa Clara, California', null, '6951');
INSERT INTO `securities` VALUES ('47', 'ADM', 'Archer-Daniels-Midland Co', 'reports', 'Consumer Staples', 'Agricultural Products', 'Decatur, Illinois', '1981-07-29', '7084');
INSERT INTO `securities` VALUES ('48', 'ARNC', 'Arconic Inc', 'reports', 'Industrials', 'Aerospace & Defense', 'New York, New York', '1964-03-31', '4281');
INSERT INTO `securities` VALUES ('49', 'AJG', 'Arthur J. Gallagher & Co.', 'reports', 'Financials', 'Insurance Brokers', 'Itasca, Illinois', '2016-05-31', '354190');
INSERT INTO `securities` VALUES ('50', 'AIZ', 'Assurant Inc', 'reports', 'Financials', 'Multi-line Insurance', 'New York, New York', '2007-04-10', '1267238');
INSERT INTO `securities` VALUES ('51', 'T', 'AT&T Inc', 'reports', 'Telecommunications Services', 'Integrated Telecommunications Services', 'Dallas, Texas', '1983-11-30', '732717');
INSERT INTO `securities` VALUES ('52', 'ADSK', 'Autodesk Inc', 'reports', 'Information Technology', 'Application Software', 'San Rafael, California', '1989-12-01', '769397');
INSERT INTO `securities` VALUES ('53', 'ADP', 'Automatic Data Processing', 'reports', 'Information Technology', 'Internet Software & Services', 'Roseland, New Jersey', '1981-03-31', '8670');
INSERT INTO `securities` VALUES ('54', 'AN', 'AutoNation Inc', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Fort Lauderdale, Florida', null, '350698');
INSERT INTO `securities` VALUES ('55', 'AZO', 'AutoZone Inc', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Memphis, Tennessee', null, '866787');
INSERT INTO `securities` VALUES ('56', 'AVB', 'AvalonBay Communities, Inc.', 'reports', 'Real Estate', 'Residential REITs', 'Arlington, Virginia[3]', '2007-01-10', '915912');
INSERT INTO `securities` VALUES ('57', 'AVY', 'Avery Dennison Corp', 'reports', 'Materials', 'Paper Packaging', 'Glendale, California', '1987-12-31', '8818');
INSERT INTO `securities` VALUES ('58', 'BHI', 'Baker Hughes Inc', 'reports', 'Energy', 'Oil & Gas Equipment & Services', 'Houston, Texas', null, '808362');
INSERT INTO `securities` VALUES ('59', 'BLL', 'Ball Corp', 'reports', 'Materials', 'Metal & Glass Containers', 'Broomfield, Colorado', '1984-10-31', '9389');
INSERT INTO `securities` VALUES ('60', 'BAC', 'Bank of America Corp', 'reports', 'Financials', 'Banks', 'Charlotte, North Carolina', '1976-06-30', '70858');
INSERT INTO `securities` VALUES ('61', 'BCR', 'Bard (C.R.) Inc.', 'reports', 'Health Care', 'Health Care Equipment', 'Murray Hill, New Jersey', '1975-06-30', '9892');
INSERT INTO `securities` VALUES ('62', 'BAX', 'Baxter International Inc.', 'reports', 'Health Care', 'Health Care Equipment', 'Deerfield, Illinois', '1972-09-30', '10456');
INSERT INTO `securities` VALUES ('63', 'BBT', 'BB&T Corporation', 'reports', 'Financials', 'Banks', 'Winston-Salem, North Carolina', null, '92230');
INSERT INTO `securities` VALUES ('64', 'BDX', 'Becton Dickinson', 'reports', 'Health Care', 'Health Care Equipment', 'Franklin Lakes, New Jersey', '1972-09-30', '10795');
INSERT INTO `securities` VALUES ('65', 'BBBY', 'Bed Bath & Beyond', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Union, New Jersey', null, '886158');
INSERT INTO `securities` VALUES ('66', 'BRK.B', 'Berkshire Hathaway', 'reports', 'Financials', 'Multi-Sector Holdings', 'Omaha, Nebraska', '2010-02-16', '1067983');
INSERT INTO `securities` VALUES ('67', 'BBY', 'Best Buy Co. Inc.', 'reports', 'Consumer Discretionary', 'Computer & Electronics Retail', 'Richfield, Minnesota', null, '764478');
INSERT INTO `securities` VALUES ('68', 'BIIB', 'BIOGEN IDEC Inc.', 'reports', 'Health Care', 'Biotechnology', 'Weston, Massachusetts', null, '875045');
INSERT INTO `securities` VALUES ('69', 'BLK', 'BlackRock', 'reports', 'Financials', 'Asset Management & Custody Banks', 'New York, New York', '2011-04-04', '1364742');
INSERT INTO `securities` VALUES ('70', 'HRB', 'Block H&R', 'reports', 'Financials', 'Consumer Finance', 'Kansas City, Missouri', '1986-11-30', '12659');
INSERT INTO `securities` VALUES ('71', 'BA', 'Boeing Company', 'reports', 'Industrials', 'Aerospace & Defense', 'Chicago, Illinois', null, '12927');
INSERT INTO `securities` VALUES ('72', 'BWA', 'BorgWarner', 'reports', 'Consumer Discretionary', 'Auto Parts & Equipment', 'Auburn Hills, Michigan', '2011-12-19', '908255');
INSERT INTO `securities` VALUES ('73', 'BXP', 'Boston Properties', 'reports', 'Real Estate', 'REITs', 'Boston, Massachusetts', null, '1037540');
INSERT INTO `securities` VALUES ('74', 'BSX', 'Boston Scientific', 'reports', 'Health Care', 'Health Care Equipment', 'Marlborough, Massachusetts[4]', null, '885725');
INSERT INTO `securities` VALUES ('75', 'BMY', 'Bristol-Myers Squibb', 'reports', 'Health Care', 'Health Care Distributors', 'New York, New York', null, '14272');
INSERT INTO `securities` VALUES ('76', 'AVGO', 'Broadcom', 'reports', 'Information Technology', 'Semiconductors', 'San Jose, California', '2014-05-08', '1441634');
INSERT INTO `securities` VALUES ('77', 'BF.B', 'Brown-Forman Corporation', 'reports', 'Consumer Staples', 'Distillers & Vintners', 'Louisville, Kentucky', '1982-10-31', '14693');
INSERT INTO `securities` VALUES ('78', 'CHRW', 'C. H. Robinson Worldwide', 'reports', 'Industrials', 'Air Freight & Logistics', 'Eden Prairie, Minnesota', null, '1043277');
INSERT INTO `securities` VALUES ('79', 'CA', 'CA, Inc.', 'reports', 'Information Technology', 'Systems Software', 'Islandia, New York', '1987-07-31', '356028');
INSERT INTO `securities` VALUES ('80', 'COG', 'Cabot Oil & Gas', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '2008-06-23', '858470');
INSERT INTO `securities` VALUES ('81', 'CPB', 'Campbell Soup', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Camden, New Jersey', null, '16732');
INSERT INTO `securities` VALUES ('82', 'COF', 'Capital One Financial', 'reports', 'Financials', 'Consumer Finance', 'Tysons Corner, Virginia', null, '927628');
INSERT INTO `securities` VALUES ('83', 'CAH', 'Cardinal Health Inc.', 'reports', 'Health Care', 'Health Care Distributors', 'Dublin, Ohio', null, '721371');
INSERT INTO `securities` VALUES ('84', 'KMX', 'Carmax Inc', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Richmond, Virginia', '2010-06-28', '1170010');
INSERT INTO `securities` VALUES ('85', 'CCL', 'Carnival Corp.', 'reports', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Miami, Florida', null, '815097');
INSERT INTO `securities` VALUES ('86', 'CAT', 'Caterpillar Inc.', 'reports', 'Industrials', 'Construction & Farm Machinery & Heavy Trucks', 'Peoria, Illinois', null, '18230');
INSERT INTO `securities` VALUES ('87', 'CBG', 'CBRE Group', 'reports', 'Real Estate', 'Real Estate Services', 'Los Angeles, California', null, '1138118');
INSERT INTO `securities` VALUES ('88', 'CBS', 'CBS Corp.', 'reports', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'New York, New York', '1994-09-01', '813828');
INSERT INTO `securities` VALUES ('89', 'CELG', 'Celgene Corp.', 'reports', 'Health Care', 'Biotechnology', 'Summit, New Jersey', null, '816284');
INSERT INTO `securities` VALUES ('90', 'CNC', 'Centene Corporation', 'reports', 'Health Care', 'Managed Health Care', 'St Louis, Missouri', '2016-03-30', '1071739');
INSERT INTO `securities` VALUES ('91', 'CNP', 'CenterPoint Energy', 'reports', 'Utilities', 'MultiUtilities', 'Houston, Texas', '1985-07-31', '1130310');
INSERT INTO `securities` VALUES ('92', 'CTL', 'CenturyLink Inc', 'reports', 'Telecommunications Services', 'Integrated Telecommunications Services', 'Monroe, Louisiana', null, '18926');
INSERT INTO `securities` VALUES ('93', 'CERN', 'Cerner', 'reports', 'Health Care', 'Health Care Technology', 'North Kansas City, Missouri', '2010-04-30', '804753');
INSERT INTO `securities` VALUES ('94', 'CF', 'CF Industries Holdings Inc', 'reports', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Deerfield, Illinois', '2008-08-27', '1324404');
INSERT INTO `securities` VALUES ('95', 'SCHW', 'Charles Schwab Corporation', 'reports', 'Financials', 'Investment Banking & Brokerage', 'San Francisco, California', null, '316709');
INSERT INTO `securities` VALUES ('96', 'CHTR', 'Charter Communications', 'reports', 'Consumer Discretionary', 'Cable & Satellite', 'Stamford, Connecticut', '2016-09-08', '1091667');
INSERT INTO `securities` VALUES ('97', 'CHK', 'Chesapeake Energy', 'reports', 'Energy', 'Integrated Oil & Gas', 'Oklahoma City, Oklahoma', null, '895126');
INSERT INTO `securities` VALUES ('98', 'CVX', 'Chevron Corp.', 'reports', 'Energy', 'Integrated Oil & Gas', 'San Ramon, California', null, '93410');
INSERT INTO `securities` VALUES ('99', 'CMG', 'Chipotle Mexican Grill', 'reports', 'Consumer Discretionary', 'Restaurants', 'Denver, Colorado', '2011-04-28', '1058090');
INSERT INTO `securities` VALUES ('100', 'CB', 'Chubb Limited', 'reports', 'Financials', 'Property & Casualty Insurance', 'Zurich, Switzerland', '2010-07-15', '896159');
INSERT INTO `securities` VALUES ('101', 'CHD', 'Church & Dwight', 'reports', 'Consumer Staples', 'Household Products', 'Ewing, New Jersey', '2015-12-29', '313927');
INSERT INTO `securities` VALUES ('102', 'CI', 'CIGNA Corp.', 'reports', 'Health Care', 'Managed Health Care', 'Philadelphia, Pennsylvania', '1976-06-30', '701221');
INSERT INTO `securities` VALUES ('103', 'XEC', 'Cimarex Energy', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Denver, Colorado', '2014-06-21', '1168054');
INSERT INTO `securities` VALUES ('104', 'CINF', 'Cincinnati Financial', 'reports', 'Financials', 'Property & Casualty Insurance', 'Fairfield, Ohio', null, '20286');
INSERT INTO `securities` VALUES ('105', 'CTAS', 'Cintas Corporation', 'reports', 'Industrials', 'Diversified Support Services', 'Mason, Ohio', null, '723254');
INSERT INTO `securities` VALUES ('106', 'CSCO', 'Cisco Systems', 'reports', 'Information Technology', 'Networking Equipment', 'San Jose, California', '1993-12-01', '858877');
INSERT INTO `securities` VALUES ('107', 'C', 'Citigroup Inc.', 'reports', 'Financials', 'Banks', 'New York, New York', '1988-05-31', '831001');
INSERT INTO `securities` VALUES ('108', 'CFG', 'Citizens Financial Group', 'reports', 'Financials', 'Regional Banks', 'Providence, Rhode Island', '2016-01-29', '759944');
INSERT INTO `securities` VALUES ('109', 'CTXS', 'Citrix Systems', 'reports', 'Information Technology', 'Internet Software & Services', 'Fort Lauderdale, Florida', null, '877890');
INSERT INTO `securities` VALUES ('110', 'CME', 'CME Group Inc.', 'reports', 'Financials', 'Financial Exchanges & Data', 'Chicago, Illinois', null, '1156375');
INSERT INTO `securities` VALUES ('111', 'CMS', 'CMS Energy', 'reports', 'Utilities', 'MultiUtilities', 'Jackson, Michigan', null, '811156');
INSERT INTO `securities` VALUES ('112', 'COH', 'Coach Inc.', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York, New York', null, '1116132');
INSERT INTO `securities` VALUES ('113', 'KO', 'Coca Cola Company', 'reports', 'Consumer Staples', 'Soft Drinks', 'Atlanta, Georgia', null, '21344');
INSERT INTO `securities` VALUES ('114', 'CTSH', 'Cognizant Technology Solutions', 'reports', 'Information Technology', 'IT Consulting & Other Services', 'Teaneck, New Jersey', null, '1058290');
INSERT INTO `securities` VALUES ('115', 'CL', 'Colgate-Palmolive', 'reports', 'Consumer Staples', 'Household Products', 'New York, New York', null, '21665');
INSERT INTO `securities` VALUES ('116', 'CMCSA', 'Comcast A Corp', 'reports', 'Consumer Discretionary', 'Cable & Satellite', 'Philadelphia, Pennsylvania', '2015-09-18', '1166691');
INSERT INTO `securities` VALUES ('117', 'CMA', 'Comerica Inc.', 'reports', 'Financials', 'Regional Banks', 'Dallas, Texas', null, '28412');
INSERT INTO `securities` VALUES ('118', 'CAG', 'ConAgra Foods Inc.', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Omaha, Nebraska', '1983-08-31', '23217');
INSERT INTO `securities` VALUES ('119', 'CXO', 'Concho Resources', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Midland, Texas', '2016-02-22', '1358071');
INSERT INTO `securities` VALUES ('120', 'COP', 'ConocoPhillips', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', null, '1163165');
INSERT INTO `securities` VALUES ('121', 'ED', 'Consolidated Edison', 'reports', 'Utilities', 'Electric Utilities', 'New York, New York', null, '1047862');
INSERT INTO `securities` VALUES ('122', 'STZ', 'Constellation Brands', 'reports', 'Consumer Staples', 'Distillers & Vintners', 'Victor, New York', null, '16918');
INSERT INTO `securities` VALUES ('123', 'GLW', 'Corning Inc.', 'reports', 'Information Technology', 'Electronic Components', 'Corning, New York', null, '24741');
INSERT INTO `securities` VALUES ('124', 'COST', 'Costco Co.', 'reports', 'Consumer Staples', 'Hypermarkets & Super Centers', 'Issaquah, Washington', '1993-10-01', '909832');
INSERT INTO `securities` VALUES ('125', 'COTY', 'Coty, Inc', 'reports', 'Consumer Staples', 'Personal Products', 'New York, NY', '2016-10-03', '1024305');
INSERT INTO `securities` VALUES ('126', 'CCI', 'Crown Castle International Corp.', 'reports', 'Real Estate', 'REITs', 'Houston, Texas', '2012-03-14', '1051470');
INSERT INTO `securities` VALUES ('127', 'CSRA', 'CSRA Inc.', 'reports', 'Information Technology', 'IT Consulting & Other Services', 'Falls Church, Virginia', '2015-12-01', '1646383');
INSERT INTO `securities` VALUES ('128', 'CSX', 'CSX Corp.', 'reports', 'Industrials', 'Railroads', 'Jacksonville, Florida', '1967-09-30', '277948');
INSERT INTO `securities` VALUES ('129', 'CMI', 'Cummins Inc.', 'reports', 'Industrials', 'Industrial Machinery', 'Columbus, Indiana', '1965-03-31', '26172');
INSERT INTO `securities` VALUES ('130', 'CVS', 'CVS Health', 'reports', 'Consumer Staples', 'Drug Retail', 'Woonsocket, Rhode Island', null, '64803');
INSERT INTO `securities` VALUES ('131', 'DHI', 'D. R. Horton', 'reports', 'Consumer Discretionary', 'Homebuilding', 'Fort Worth, Texas', null, '882184');
INSERT INTO `securities` VALUES ('132', 'DHR', 'Danaher Corp.', 'reports', 'Industrials', 'Industrial Conglomerates', 'Washington, D.C.', null, '313616');
INSERT INTO `securities` VALUES ('133', 'DRI', 'Darden Restaurants', 'reports', 'Consumer Discretionary', 'Restaurants', 'Orlando, Florida', null, '940944');
INSERT INTO `securities` VALUES ('134', 'DVA', 'DaVita Inc.', 'reports', 'Health Care', 'Health Care Facilities', 'Denver, Colorado', '2008-07-31', '927066');
INSERT INTO `securities` VALUES ('135', 'DE', 'Deere & Co.', 'reports', 'Industrials', 'Construction & Farm Machinery & Heavy Trucks', 'Moline, Illinois', null, '315189');
INSERT INTO `securities` VALUES ('136', 'DLPH', 'Delphi Automotive', 'reports', 'Consumer Discretionary', 'Auto Parts & Equipment', 'Gillingham, Kent, United Kingdom', '2012-12-24', '1521332');
INSERT INTO `securities` VALUES ('137', 'DAL', 'Delta Air Lines', 'reports', 'Industrials', 'Airlines', 'Atlanta, Georgia', '2013-09-11', '27904');
INSERT INTO `securities` VALUES ('138', 'XRAY', 'Dentsply Sirona', 'reports', 'Health Care', 'Health Care Supplies', 'York, Pennsylvania', '2008-11-14', '818479');
INSERT INTO `securities` VALUES ('139', 'DVN', 'Devon Energy Corp.', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Oklahoma City, Oklahoma', null, '1090012');
INSERT INTO `securities` VALUES ('140', 'DLR', 'Digital Realty Trust', 'reports', 'Real Estate', 'Specialized REITs', 'San Francisco, California', '2016-05-18', '1297996');
INSERT INTO `securities` VALUES ('141', 'DFS', 'Discover Financial Services', 'reports', 'Financials', 'Consumer Finance', 'Riverwoods, Illinois', '2007-07-02', '1393612');
INSERT INTO `securities` VALUES ('142', 'DISCA', 'Discovery Communications-A', 'reports', 'Consumer Discretionary', 'Cable & Satellite', 'Silver Spring, Maryland', '2010-03-01', '1437107');
INSERT INTO `securities` VALUES ('143', 'DISCK', 'Discovery Communications-C', 'reports', 'Consumer Discretionary', 'Cable & Satellite', 'Silver Spring, Maryland', '2014-08-07', '1437107');
INSERT INTO `securities` VALUES ('144', 'DG', 'Dollar General', 'reports', 'Consumer Discretionary', 'General Merchandise Stores', 'Goodlettsville, Tennessee', '2012-12-03', '29534');
INSERT INTO `securities` VALUES ('145', 'DLTR', 'Dollar Tree', 'reports', 'Consumer Discretionary', 'General Merchandise Stores', 'Chesapeake, Virginia', '2011-12-19', '935703');
INSERT INTO `securities` VALUES ('146', 'D', 'Dominion Resources', 'reports', 'Utilities', 'Electric Utilities', 'Richmond, Virginia', null, '715957');
INSERT INTO `securities` VALUES ('147', 'DOV', 'Dover Corp.', 'reports', 'Industrials', 'Industrial Machinery', 'Downers Grove, Illinois', '1985-10-31', '29905');
INSERT INTO `securities` VALUES ('148', 'DOW', 'Dow Chemical', 'reports', 'Materials', 'Diversified Chemicals', 'Midland, Michigan', null, '29915');
INSERT INTO `securities` VALUES ('149', 'DPS', 'Dr Pepper Snapple Group', 'reports', 'Consumer Staples', 'Soft Drinks', 'Plano, Texas', '2008-10-07', '1418135');
INSERT INTO `securities` VALUES ('150', 'DTE', 'DTE Energy Co.', 'reports', 'Utilities', 'MultiUtilities', 'Detroit, Michigan', null, '936340');
INSERT INTO `securities` VALUES ('151', 'DD', 'Du Pont (E.I.)', 'reports', 'Materials', 'Diversified Chemicals', 'Wilmington, Delaware', null, '30554');
INSERT INTO `securities` VALUES ('152', 'DUK', 'Duke Energy', 'reports', 'Utilities', 'Electric Utilities', 'Charlotte, North Carolina', '1976-06-30', '1326160');
INSERT INTO `securities` VALUES ('153', 'DNB', 'Dun & Bradstreet', 'reports', 'Industrials', 'Research & Consulting Services', 'Short Hills, New Jersey', '2008-12-02', '1115222');
INSERT INTO `securities` VALUES ('154', 'ETFC', 'E*Trade', 'reports', 'Financials', 'Investment Banking & Brokerage', 'New York, New York', '2004-03-31', '1015780');
INSERT INTO `securities` VALUES ('155', 'EMN', 'Eastman Chemical', 'reports', 'Materials', 'Diversified Chemicals', 'Kingsport, Tennessee', '1994-01-01', '915389');
INSERT INTO `securities` VALUES ('156', 'ETN', 'Eaton Corporation', 'reports', 'Industrials', 'Industrial Conglomerates', 'Dublin, Ireland', null, '1551182');
INSERT INTO `securities` VALUES ('157', 'EBAY', 'eBay Inc.', 'reports', 'Information Technology', 'Internet Software & Services', 'San Jose, California', null, '1065088');
INSERT INTO `securities` VALUES ('158', 'ECL', 'Ecolab Inc.', 'reports', 'Materials', 'Specialty Chemicals', 'St. Paul, Minnesota', '1989-01-31', '31462');
INSERT INTO `securities` VALUES ('159', 'EIX', 'Edison Int\'l', 'reports', 'Utilities', 'Electric Utilities', 'Rosemead, California', null, '827052');
INSERT INTO `securities` VALUES ('160', 'EW', 'Edwards Lifesciences', 'reports', 'Health Care', 'Health Care Equipment', 'Irvine, California', '2011-04-01', '1099800');
INSERT INTO `securities` VALUES ('161', 'EA', 'Electronic Arts', 'reports', 'Information Technology', 'Home Entertainment Software', 'Redwood City, California', null, '712515');
INSERT INTO `securities` VALUES ('162', 'EMR', 'Emerson Electric Company', 'reports', 'Industrials', 'Industrial Conglomerates', 'Ferguson, Missouri', '1965-03-31', '32604');
INSERT INTO `securities` VALUES ('163', 'ENDP', 'Endo International', 'reports', 'Health Care', 'Pharmaceuticals', 'Dublin, Ireland', '2015-01-27', '1100962');
INSERT INTO `securities` VALUES ('164', 'ETR', 'Entergy Corp.', 'reports', 'Utilities', 'Electric Utilities', 'New Orleans, Louisiana', null, '65984');
INSERT INTO `securities` VALUES ('165', 'EVHC', 'Envision Healthcare Corp', 'reports', 'Health Care', 'Health Care Services', 'Nashville, Tennessee', '2016-12-02', '895930');
INSERT INTO `securities` VALUES ('166', 'EOG', 'EOG Resources', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', null, '821189');
INSERT INTO `securities` VALUES ('167', 'EQT', 'EQT Corporation', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Pittsburgh, Pennsylvania', '2008-12-19', '33213');
INSERT INTO `securities` VALUES ('168', 'EFX', 'Equifax Inc.', 'reports', 'Industrials', 'Research & Consulting Services', 'Atlanta, Georgia', null, '33185');
INSERT INTO `securities` VALUES ('169', 'EQIX', 'Equinix', 'reports', 'Real Estate', 'REITs', 'Redwood City, California', '2015-03-20', '1101239');
INSERT INTO `securities` VALUES ('170', 'EQR', 'Equity Residential', 'reports', 'Real Estate', 'REITs', 'Chicago, Illinois', null, '906107');
INSERT INTO `securities` VALUES ('171', 'ESS', 'Essex Property Trust, Inc.', 'reports', 'Real Estate', 'Residential REITs', 'Palo Alto, California', '2014-04-02', '920522');
INSERT INTO `securities` VALUES ('172', 'EL', 'Estee Lauder Cos.', 'reports', 'Consumer Staples', 'Personal Products', 'New York, New York', null, '1001250');
INSERT INTO `securities` VALUES ('173', 'ES', 'Eversource Energy', 'reports', 'Utilities', 'MultiUtilities', 'Springfield, Massachusetts', null, '72741');
INSERT INTO `securities` VALUES ('174', 'EXC', 'Exelon Corp.', 'reports', 'Utilities', 'MultiUtilities', 'Chicago, Illinois', null, '1109357');
INSERT INTO `securities` VALUES ('175', 'EXPE', 'Expedia Inc.', 'reports', 'Consumer Discretionary', 'Internet & Direct Marketing Retail', 'Bellevue, Washington', '2007-10-02', '1324424');
INSERT INTO `securities` VALUES ('176', 'EXPD', 'Expeditors Int\'l', 'reports', 'Industrials', 'Air Freight & Logistics', 'Seattle, Washington', '2007-10-10', '746515');
INSERT INTO `securities` VALUES ('177', 'ESRX', 'Express Scripts', 'reports', 'Health Care', 'Health Care Distributors', 'Cool Valley, Missouri', '2003-09-25', '1532063');
INSERT INTO `securities` VALUES ('178', 'EXR', 'Extra Space Storage', 'reports', 'Real Estate', 'Specialized REITs', 'Salt Lake City, UT', '2016-01-19', '1289490');
INSERT INTO `securities` VALUES ('179', 'XOM', 'Exxon Mobil Corp.', 'reports', 'Energy', 'Integrated Oil & Gas', 'Irving, Texas', null, '34088');
INSERT INTO `securities` VALUES ('180', 'FFIV', 'F5 Networks', 'reports', 'Information Technology', 'Networking Equipment', 'Seattle, Washington', '2010-12-20', '1048695');
INSERT INTO `securities` VALUES ('181', 'FB', 'Facebook', 'reports', 'Information Technology', 'Internet Software & Services', 'Menlo Park, California', '2013-12-23', '1326801');
INSERT INTO `securities` VALUES ('182', 'FAST', 'Fastenal Co', 'reports', 'Industrials', 'Building Products', 'Winona, Minnesota', '2009-09-15', '815556');
INSERT INTO `securities` VALUES ('183', 'FRT', 'Federal Realty Investment Trust', 'reports', 'Real Estate', 'Retail REITs', 'Rockville, Maryland', '2016-02-01', '34903');
INSERT INTO `securities` VALUES ('184', 'FDX', 'FedEx Corporation', 'reports', 'Industrials', 'Air Freight & Logistics', 'Memphis, Tennessee', '1980-12-31', '1048911');
INSERT INTO `securities` VALUES ('185', 'FIS', 'Fidelity National Information Services', 'reports', 'Information Technology', 'Internet Software & Services', 'Jacksonville, Florida', null, '1136893');
INSERT INTO `securities` VALUES ('186', 'FITB', 'Fifth Third Bancorp', 'reports', 'Financials', 'Banks', 'Cincinnati, Ohio', null, '35527');
INSERT INTO `securities` VALUES ('187', 'FSLR', 'First Solar Inc', 'reports', 'Information Technology', 'Semiconductors', 'Tempe, Arizona', '2009-10-16', '1274494');
INSERT INTO `securities` VALUES ('188', 'FE', 'FirstEnergy Corp', 'reports', 'Utilities', 'Electric Utilities', 'Akron, Ohio', null, '1031296');
INSERT INTO `securities` VALUES ('189', 'FISV', 'Fiserv Inc', 'reports', 'Information Technology', 'Internet Software & Services', 'Brookfield, Wisconsin', null, '798354');
INSERT INTO `securities` VALUES ('190', 'FLIR', 'FLIR Systems', 'reports', 'Information Technology', 'Electronic Equipment & Instruments', 'Wilsonville, Oregon', '2009-01-02', '354908');
INSERT INTO `securities` VALUES ('191', 'FLS', 'Flowserve Corporation', 'reports', 'Industrials', 'Industrial Machinery', 'Irving, Texas', '2008-10-02', '30625');
INSERT INTO `securities` VALUES ('192', 'FLR', 'Fluor Corp.', 'reports', 'Industrials', 'Diversified Commercial Services', 'Irving, Texas', '1980-03-31', '1124198');
INSERT INTO `securities` VALUES ('193', 'FMC', 'FMC Corporation', 'reports', 'Materials', 'Diversified Chemicals', 'Philadelphia, Pennsylvania', '2009-08-19', '37785');
INSERT INTO `securities` VALUES ('194', 'FTI', 'FMC Technologies Inc.', 'reports', 'Energy', 'Oil & Gas Equipment & Services', 'Houston, Texas', '2009-06-05', '1135152');
INSERT INTO `securities` VALUES ('195', 'FL', 'Foot Locker Inc', 'reports', 'Consumer Discretionary', 'Apparel Retail', 'New York, New York', '2016-04-04', '850209');
INSERT INTO `securities` VALUES ('196', 'F', 'Ford Motor', 'reports', 'Consumer Discretionary', 'Automobile Manufacturers', 'Dearborn, Michigan', null, '37996');
INSERT INTO `securities` VALUES ('197', 'FTV', 'Fortive Corp', 'reports', 'Industrials', 'Industrial Machinery', 'Everett, Washington', '2016-07-01', '1659166');
INSERT INTO `securities` VALUES ('198', 'FBHS', 'Fortune Brands Home & Security', 'reports', 'Industrials', 'Building Products', 'Deerfield, Illinois', '2016-06-22', '1519751');
INSERT INTO `securities` VALUES ('199', 'BEN', 'Franklin Resources', 'reports', 'Financials', 'Asset Management & Custody Banks', 'San Mateo, California', null, '38777');
INSERT INTO `securities` VALUES ('200', 'FCX', 'Freeport-McMoran Cp & Gld', 'reports', 'Materials', 'Copper', 'Phoenix, Arizona', null, '831259');
INSERT INTO `securities` VALUES ('201', 'FTR', 'Frontier Communications', 'reports', 'Telecommunications Services', 'Integrated Telecommunications Services', 'Stamford, Connecticut', null, '20520');
INSERT INTO `securities` VALUES ('202', 'GPS', 'Gap (The)', 'reports', 'Consumer Discretionary', 'Apparel Retail', 'San Francisco, California', '1986-08-31', '39911');
INSERT INTO `securities` VALUES ('203', 'GRMN', 'Garmin Ltd.', 'reports', 'Consumer Discretionary', 'Consumer Electronics', 'Schaffhausen, Switzerland', '2012-12-12', '1121788');
INSERT INTO `securities` VALUES ('204', 'GD', 'General Dynamics', 'reports', 'Industrials', 'Aerospace & Defense', 'Falls Church, Virginia', null, '40533');
INSERT INTO `securities` VALUES ('205', 'GE', 'General Electric', 'reports', 'Industrials', 'Industrial Conglomerates', 'Fairfield, Connecticut', null, '40545');
INSERT INTO `securities` VALUES ('206', 'GGP', 'General Growth Properties Inc.', 'reports', 'Real Estate', 'Retail REITs', 'Chicago, Illinois', '2013-12-10', '895648');
INSERT INTO `securities` VALUES ('207', 'GIS', 'General Mills', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Golden Valley, Minnesota', '1969-03-31', '40704');
INSERT INTO `securities` VALUES ('208', 'GM', 'General Motors', 'reports', 'Consumer Discretionary', 'Automobile Manufacturers', 'Detroit, Michigan', '2013-06-06', '1467858');
INSERT INTO `securities` VALUES ('209', 'GPC', 'Genuine Parts', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Atlanta, Georgia', '1973-12-31', '40987');
INSERT INTO `securities` VALUES ('210', 'GILD', 'Gilead Sciences', 'reports', 'Health Care', 'Biotechnology', 'Foster City, California', null, '882095');
INSERT INTO `securities` VALUES ('211', 'GPN', 'Global Payments Inc', 'reports', 'Information Technology', 'Data Processing & Outsourced Services', 'Atlanta, Georgia', '2016-04-25', '1123360');
INSERT INTO `securities` VALUES ('212', 'GS', 'Goldman Sachs Group', 'reports', 'Financials', 'Investment Banking & Brokerage', 'New York, New York', null, '886982');
INSERT INTO `securities` VALUES ('213', 'GT', 'Goodyear Tire & Rubber', 'reports', 'Consumer Discretionary', 'Tires & Rubber', 'Akron, Ohio', null, '42582');
INSERT INTO `securities` VALUES ('214', 'GWW', 'Grainger (W.W.) Inc.', 'reports', 'Industrials', 'Industrial Materials', 'Lake Forest, Illinois', '1981-06-30', '277135');
INSERT INTO `securities` VALUES ('215', 'HAL', 'Halliburton Co.', 'reports', 'Energy', 'Oil & Gas Equipment & Services', 'Houston, Texas', null, '45012');
INSERT INTO `securities` VALUES ('216', 'HBI', 'Hanesbrands Inc', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Winston-Salem, North Carolina', '2015-03-20', '1359841');
INSERT INTO `securities` VALUES ('217', 'HOG', 'Harley-Davidson', 'reports', 'Consumer Discretionary', 'Motorcycle Manufacturers', 'Milwaukee, Wisconsin', null, '793952');
INSERT INTO `securities` VALUES ('218', 'HAR', 'Harman Int\'l Industries', 'reports', 'Consumer Discretionary', 'Consumer Electronics', 'Stamford, Connecticut', null, '800459');
INSERT INTO `securities` VALUES ('219', 'HRS', 'Harris Corporation', 'reports', 'Information Technology', 'Telecommunications Equipment', 'Melbourne, Florida', '2008-09-22', '202058');
INSERT INTO `securities` VALUES ('220', 'HIG', 'Hartford Financial Svc.Gp.', 'reports', 'Financials', 'Property & Casualty Insurance', 'Hartford, Connecticut', null, '874766');
INSERT INTO `securities` VALUES ('221', 'HAS', 'Hasbro Inc.', 'reports', 'Consumer Discretionary', 'Leisure Products', 'Pawtucket, Rhode Island', '1984-09-30', '46080');
INSERT INTO `securities` VALUES ('222', 'HCA', 'HCA Holdings', 'reports', 'Health Care', 'Health Care Facilities', 'Nashville, Tennessee', '2015-01-27', '860730');
INSERT INTO `securities` VALUES ('223', 'HCP', 'HCP Inc.', 'reports', 'Real Estate', 'REITs', 'Long Beach, California', '2008-03-31', '765880');
INSERT INTO `securities` VALUES ('224', 'HP', 'Helmerich & Payne', 'reports', 'Energy', 'Oil & Gas Drilling', 'Tulsa, Oklahoma[5]', null, '46765');
INSERT INTO `securities` VALUES ('225', 'HSIC', 'Henry Schein', 'reports', 'Health Care', 'Health Care Distributors', 'Melville, New York', '2015-03-17', '1000228');
INSERT INTO `securities` VALUES ('226', 'HES', 'Hess Corporation', 'reports', 'Energy', 'Integrated Oil & Gas', 'New York, New York', '1984-05-31', '4447');
INSERT INTO `securities` VALUES ('227', 'HPE', 'Hewlett Packard Enterprise', 'reports', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'Palo Alto, California', '2015-11-02', '1645590');
INSERT INTO `securities` VALUES ('228', 'HOLX', 'Hologic', 'reports', 'Health Care', 'Health Care Equipment', 'Marlborough, Massachusetts', '2016-03-30', '859737');
INSERT INTO `securities` VALUES ('229', 'HD', 'Home Depot', 'reports', 'Consumer Discretionary', 'Home Improvement Retail', 'Atlanta, Georgia', '1988-03-31', '354950');
INSERT INTO `securities` VALUES ('230', 'HON', 'Honeywell Int\'l Inc.', 'reports', 'Industrials', 'Industrial Conglomerates', 'Morristown, New Jersey', '1964-03-31', '773840');
INSERT INTO `securities` VALUES ('231', 'HRL', 'Hormel Foods Corp.', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Austin, Minnesota', '2009-03-04', '48465');
INSERT INTO `securities` VALUES ('232', 'HST', 'Host Hotels & Resorts', 'reports', 'Real Estate', 'REITs', 'Bethesda, Maryland', '2007-03-20', '1070750');
INSERT INTO `securities` VALUES ('233', 'HPQ', 'HP Inc.', 'reports', 'Information Technology', 'Computer Hardware', 'Palo Alto, California', '1974-12-31', '47217');
INSERT INTO `securities` VALUES ('234', 'HUM', 'Humana Inc.', 'reports', 'Health Care', 'Managed Health Care', 'Louisville, Kentucky', null, '49071');
INSERT INTO `securities` VALUES ('235', 'HBAN', 'Huntington Bancshares', 'reports', 'Financials', 'Banks', 'Columbus, Ohio', null, '49196');
INSERT INTO `securities` VALUES ('236', 'IDXX', 'IDEXX Laboratories', 'reports', 'Health Care', 'Health Care Equipment', 'Westbrook, Maine', '2017-01-05', '874716');
INSERT INTO `securities` VALUES ('237', 'ITW', 'Illinois Tool Works', 'reports', 'Industrials', 'Industrial Machinery', 'Glenview, Illinois', '1986-02-28', '49826');
INSERT INTO `securities` VALUES ('238', 'ILMN', 'Illumina Inc', 'reports', 'Health Care', 'Life Sciences Tools & Services', 'San Diego, California', '2015-11-19', '1110803');
INSERT INTO `securities` VALUES ('239', 'IR', 'Ingersoll-Rand PLC', 'reports', 'Industrials', 'Industrial Conglomerates', 'Dublin, Ireland', '2010-11-17', '1466258');
INSERT INTO `securities` VALUES ('240', 'INTC', 'Intel Corp.', 'reports', 'Information Technology', 'Semiconductors', 'Santa Clara, California', '1976-12-31', '50863');
INSERT INTO `securities` VALUES ('241', 'ICE', 'Intercontinental Exchange', 'reports', 'Financials', 'Diversified Financial Services', 'Atlanta, Georgia', '2007-09-26', '1571949');
INSERT INTO `securities` VALUES ('242', 'IBM', 'International Business Machines', 'reports', 'Information Technology', 'IT Consulting & Other Services', 'Armonk, New York', null, '51143');
INSERT INTO `securities` VALUES ('243', 'IP', 'International Paper', 'reports', 'Materials', 'Paper Packaging', 'Memphis, Tennessee', null, '51434');
INSERT INTO `securities` VALUES ('244', 'IPG', 'Interpublic Group', 'reports', 'Consumer Discretionary', 'Advertising', 'New York, New York', '1992-10-01', '51644');
INSERT INTO `securities` VALUES ('245', 'IFF', 'Intl Flavors & Fragrances', 'reports', 'Materials', 'Specialty Chemicals', 'New York, New York', '1976-03-31', '51253');
INSERT INTO `securities` VALUES ('246', 'INTU', 'Intuit Inc.', 'reports', 'Information Technology', 'Internet Software & Services', 'Mountain View, California', '2000-12-05', '896878');
INSERT INTO `securities` VALUES ('247', 'ISRG', 'Intuitive Surgical Inc.', 'reports', 'Health Care', 'Health Care Equipment', 'Sunnyvale, California', '2008-06-02', '1035267');
INSERT INTO `securities` VALUES ('248', 'IVZ', 'Invesco Ltd.', 'reports', 'Financials', 'Asset Management & Custody Banks', 'Atlanta, Georgia', '2008-08-21', '914208');
INSERT INTO `securities` VALUES ('249', 'IRM', 'Iron Mountain Incorporated', 'reports', 'Real Estate', 'REITs', 'Boston, Massachusetts', '2009-01-06', '1020569');
INSERT INTO `securities` VALUES ('250', 'JBHT', 'J. B. Hunt Transport Services', 'reports', 'Industrials', 'Trucking', 'Lowell, Arkansas', '2015-07-01', '728535');
INSERT INTO `securities` VALUES ('251', 'JEC', 'Jacobs Engineering Group', 'reports', 'Industrials', 'Industrial Conglomerates', 'Pasadena, California', '2007-10-26', '52988');
INSERT INTO `securities` VALUES ('252', 'SJM', 'JM Smucker', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Orrville, Ohio', '2008-11-06', '91419');
INSERT INTO `securities` VALUES ('253', 'JNJ', 'Johnson & Johnson', 'reports', 'Health Care', 'Health Care Equipment', 'New Brunswick, New Jersey', '1973-06-30', '200406');
INSERT INTO `securities` VALUES ('254', 'JCI', 'Johnson Controls International', 'reports', 'Industrials', 'Building Products', 'Cork, Ireland', '2010-08-27', '833444');
INSERT INTO `securities` VALUES ('255', 'JPM', 'JPMorgan Chase & Co.', 'reports', 'Financials', 'Banks', 'New York, New York', '1975-06-30', '19617');
INSERT INTO `securities` VALUES ('256', 'JNPR', 'Juniper Networks', 'reports', 'Information Technology', 'Networking Equipment', 'Sunnyvale, California', null, '1043604');
INSERT INTO `securities` VALUES ('257', 'KSU', 'Kansas City Southern', 'reports', 'Industrials', 'Railroads', 'Kansas City, Missouri', '2013-05-24', '54480');
INSERT INTO `securities` VALUES ('258', 'K', 'Kellogg Co.', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Battle Creek, Michigan', null, '55067');
INSERT INTO `securities` VALUES ('259', 'KEY', 'KeyCorp', 'reports', 'Financials', 'Banks', 'Cleveland, Ohio', '1994-03-01', '91576');
INSERT INTO `securities` VALUES ('260', 'KMB', 'Kimberly-Clark', 'reports', 'Consumer Staples', 'Household Products', 'Irving, Texas', null, '55785');
INSERT INTO `securities` VALUES ('261', 'KIM', 'Kimco Realty', 'reports', 'Real Estate', 'REITs', 'New Hyde Park, New York', null, '879101');
INSERT INTO `securities` VALUES ('262', 'KMI', 'Kinder Morgan', 'reports', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'Houston, Texas', '2012-05-25', '1506307');
INSERT INTO `securities` VALUES ('263', 'KLAC', 'KLA-Tencor Corp.', 'reports', 'Information Technology', 'Semiconductor Equipment', 'Milpitas, California', null, '319201');
INSERT INTO `securities` VALUES ('264', 'KSS', 'Kohl\'s Corp.', 'reports', 'Consumer Discretionary', 'General Merchandise Stores', 'Menomonee Falls, Wisconsin', null, '885639');
INSERT INTO `securities` VALUES ('265', 'KHC', 'Kraft Heinz Co', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Pittsburgh, Pennsylvania', '2015-07-06', '1545158');
INSERT INTO `securities` VALUES ('266', 'KR', 'Kroger Co.', 'reports', 'Consumer Staples', 'Food Retail', 'Cincinnati, Ohio', null, '56873');
INSERT INTO `securities` VALUES ('267', 'LB', 'L Brands Inc.', 'reports', 'Consumer Discretionary', 'Apparel Retail', 'Columbus, Ohio', '1983-09-30', '701985');
INSERT INTO `securities` VALUES ('268', 'LLL', 'L-3 Communications Holdings', 'reports', 'Industrials', 'Industrial Conglomerates', 'New York, New York', null, '1056239');
INSERT INTO `securities` VALUES ('269', 'LH', 'Laboratory Corp. of America Holding', 'reports', 'Health Care', 'Health Care Facilities', 'Burlington, North Carolina', null, '920148');
INSERT INTO `securities` VALUES ('270', 'LRCX', 'Lam Research', 'reports', 'Information Technology', 'Semiconductor Equipment', 'Fremont, California', '2012-06-29', '707549');
INSERT INTO `securities` VALUES ('271', 'LEG', 'Leggett & Platt', 'reports', 'Industrials', 'Industrial Conglomerates', 'Carthage, Missouri', null, '58492');
INSERT INTO `securities` VALUES ('272', 'LEN', 'Lennar Corp.', 'reports', 'Consumer Discretionary', 'Homebuilding', 'Miami, Florida', null, '920760');
INSERT INTO `securities` VALUES ('273', 'LUK', 'Leucadia National Corp.', 'reports', 'Financials', 'Multi-Sector Holdings', 'New York, New York', '2007-08-27', '96223');
INSERT INTO `securities` VALUES ('274', 'LVLT', 'Level 3 Communications', 'reports', 'Telecommunications Services', 'Alternative Carriers', 'Broomfield, Colorado', '2014-11-05', '794323');
INSERT INTO `securities` VALUES ('275', 'LLY', 'Lilly (Eli) & Co.', 'reports', 'Health Care', 'Pharmaceuticals', 'Indianapolis, Indiana', '1970-12-31', '59478');
INSERT INTO `securities` VALUES ('276', 'LNC', 'Lincoln National', 'reports', 'Financials', 'Multi-line Insurance', 'Radnor, Pennsylvania', '1976-06-30', '59558');
INSERT INTO `securities` VALUES ('277', 'LLTC', 'Linear Technology Corp.', 'reports', 'Information Technology', 'Semiconductors', 'Milpitas, California', null, '791907');
INSERT INTO `securities` VALUES ('278', 'LKQ', 'LKQ Corporation', 'reports', 'Consumer Discretionary', 'Distributors', 'Chicago, Illinois', '2016-05-23', '1065696');
INSERT INTO `securities` VALUES ('279', 'LMT', 'Lockheed Martin Corp.', 'reports', 'Industrials', 'Aerospace & Defense', 'Bethesda, Maryland', '1984-07-31', '936468');
INSERT INTO `securities` VALUES ('280', 'L', 'Loews Corp.', 'reports', 'Financials', 'Multi-Sector Holdings', 'New York, New York', null, '60086');
INSERT INTO `securities` VALUES ('281', 'LOW', 'Lowe\'s Cos.', 'reports', 'Consumer Discretionary', 'Home Improvement Retail', 'Mooresville, North Carolina', '1984-02-29', '60667');
INSERT INTO `securities` VALUES ('282', 'LYB', 'LyondellBasell', 'reports', 'Materials', 'Diversified Chemicals', 'Rotterdam, Netherlands', '2012-09-05', '1489393');
INSERT INTO `securities` VALUES ('283', 'MTB', 'M&T Bank Corp.', 'reports', 'Financials', 'Banks', 'Buffalo, New York', null, '36270');
INSERT INTO `securities` VALUES ('284', 'MAC', 'Macerich', 'reports', 'Real Estate', 'Retail REITs', 'Santa Monica, California', '2013-05-09', '912242');
INSERT INTO `securities` VALUES ('285', 'M', 'Macy\'s Inc.', 'reports', 'Consumer Discretionary', 'Department Stores', 'Cincinnati, Ohio', null, '794367');
INSERT INTO `securities` VALUES ('286', 'MNK', 'Mallinckrodt Plc', 'reports', 'Health Care', 'Pharmaceuticals', 'Dublin, Ireland', '2014-08-19', '1567892');
INSERT INTO `securities` VALUES ('287', 'MRO', 'Marathon Oil Corp.', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '1991-05-01', '101778');
INSERT INTO `securities` VALUES ('288', 'MPC', 'Marathon Petroleum', 'reports', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'Findlay, Ohio', '2011-07-01', '1510295');
INSERT INTO `securities` VALUES ('289', 'MAR', 'Marriott Int\'l.', 'reports', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Bethesda, Maryland', null, '1048286');
INSERT INTO `securities` VALUES ('290', 'MMC', 'Marsh & McLennan', 'reports', 'Financials', 'Insurance Brokers', 'New York, New York', '1987-08-31', '62709');
INSERT INTO `securities` VALUES ('291', 'MLM', 'Martin Marietta Materials', 'reports', 'Materials', 'Construction Materials', 'Raleigh, North Carolina', '2014-07-02', '916076');
INSERT INTO `securities` VALUES ('292', 'MAS', 'Masco Corp.', 'reports', 'Industrials', 'Building Products', 'Taylor, Michigan', '1981-06-30', '62996');
INSERT INTO `securities` VALUES ('293', 'MA', 'Mastercard Inc.', 'reports', 'Information Technology', 'Internet Software & Services', 'Harrison, New York', '2008-07-18', '1141391');
INSERT INTO `securities` VALUES ('294', 'MAT', 'Mattel Inc.', 'reports', 'Consumer Discretionary', 'Leisure Products', 'El Segundo, California', '1982-03-31', '63276');
INSERT INTO `securities` VALUES ('295', 'MKC', 'McCormick & Co.', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Sparks, Maryland', null, '63754');
INSERT INTO `securities` VALUES ('296', 'MCD', 'McDonald\'s Corp.', 'reports', 'Consumer Discretionary', 'Restaurants', 'Oak Brook, Illinois', '1970-06-30', '63908');
INSERT INTO `securities` VALUES ('297', 'MCK', 'McKesson Corp.', 'reports', 'Health Care', 'Health Care Distributors', 'San Francisco, California', null, '927653');
INSERT INTO `securities` VALUES ('298', 'MJN', 'Mead Johnson', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Glenview, Illinois', '2009-12-21', '1452575');
INSERT INTO `securities` VALUES ('299', 'MDT', 'Medtronic plc', 'reports', 'Health Care', 'Health Care Equipment', 'Dublin, Ireland', '1986-10-31', '64670');
INSERT INTO `securities` VALUES ('300', 'MRK', 'Merck & Co.', 'reports', 'Health Care', 'Pharmaceuticals', 'Whitehouse Station, New Jersey', null, '310158');
INSERT INTO `securities` VALUES ('301', 'MET', 'MetLife Inc.', 'reports', 'Financials', 'Life & Health Insurance', 'New York, New York', null, '1099219');
INSERT INTO `securities` VALUES ('302', 'MTD', 'Mettler Toledo', 'reports', 'Health Care', 'Life Sciences Tools & Services', 'Columbus, Ohio', '2016-09-06', '1037646');
INSERT INTO `securities` VALUES ('303', 'KORS', 'Michael Kors Holdings', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York, New York', '2013-11-13', '1530721');
INSERT INTO `securities` VALUES ('304', 'MCHP', 'Microchip Technology', 'reports', 'Information Technology', 'Semiconductors', 'Chandler, Arizona', '2007-09-07', '827054');
INSERT INTO `securities` VALUES ('305', 'MU', 'Micron Technology', 'reports', 'Information Technology', 'Semiconductors', 'Boise, Idaho', '1994-09-27', '723125');
INSERT INTO `securities` VALUES ('306', 'MSFT', 'Microsoft Corp.', 'reports', 'Information Technology', 'Systems Software', 'Redmond, Washington', '1994-06-01', '789019');
INSERT INTO `securities` VALUES ('307', 'MAA', 'Mid-America Apartments', 'reports', 'Real Estate', 'Residential REITs', 'Memphis, Tennessee', '2016-12-02', '912595');
INSERT INTO `securities` VALUES ('308', 'MHK', 'Mohawk Industries', 'reports', 'Consumer Discretionary', 'Home Furnishings', 'Amsterdam, New York', '2013-12-23', '851968');
INSERT INTO `securities` VALUES ('309', 'TAP', 'Molson Coors Brewing Company', 'reports', 'Consumer Staples', 'Brewers', 'Denver, Colorado', '1976-06-30', '24545');
INSERT INTO `securities` VALUES ('310', 'MDLZ', 'Mondelez International', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Northfield, Illinois', '2012-10-02', '1103982');
INSERT INTO `securities` VALUES ('311', 'MON', 'Monsanto Co.', 'reports', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Creve Coeur, Missouri', '2002-08-07', '1110783');
INSERT INTO `securities` VALUES ('312', 'MNST', 'Monster Beverage', 'reports', 'Consumer Staples', 'Soft Drinks', 'Corona, California', '2012-06-28', '865752');
INSERT INTO `securities` VALUES ('313', 'MCO', 'Moody\'s Corp', 'reports', 'Financials', 'Diversified Financial Services', 'New York, New York', null, '1059556');
INSERT INTO `securities` VALUES ('314', 'MS', 'Morgan Stanley', 'reports', 'Financials', 'Investment Banking & Brokerage', 'New York, New York', null, '895421');
INSERT INTO `securities` VALUES ('315', 'MSI', 'Motorola Solutions Inc.', 'reports', 'Information Technology', 'Telecommunications Equipment', 'Schaumburg, Illinois', null, '68505');
INSERT INTO `securities` VALUES ('316', 'MUR', 'Murphy Oil', 'reports', 'Energy', 'Integrated Oil & Gas', 'El Dorado, Arkansas', null, '717423');
INSERT INTO `securities` VALUES ('317', 'MYL', 'Mylan N.V.', 'reports', 'Health Care', 'Pharmaceuticals', 'Amsterdam, Netherlands', null, '69499');
INSERT INTO `securities` VALUES ('318', 'NDAQ', 'NASDAQ OMX Group', 'reports', 'Financials', 'Diversified Financial Services', 'New York, New York', '2008-10-22', '1120193');
INSERT INTO `securities` VALUES ('319', 'NOV', 'National Oilwell Varco Inc.', 'reports', 'Energy', 'Oil & Gas Equipment & Services', 'Houston, Texas', null, '1021860');
INSERT INTO `securities` VALUES ('320', 'NAVI', 'Navient', 'reports', 'Financials', 'Consumer Finance', 'Newark, Delaware', '2014-05-01', '1593538');
INSERT INTO `securities` VALUES ('321', 'NTAP', 'NetApp', 'reports', 'Information Technology', 'Internet Software & Services', 'Sunnyvale, California', null, '1002047');
INSERT INTO `securities` VALUES ('322', 'NFLX', 'Netflix Inc.', 'reports', 'Information Technology', 'Internet Software & Services', 'Los Gatos, California', '2010-12-20', '1065280');
INSERT INTO `securities` VALUES ('323', 'NWL', 'Newell Brands', 'reports', 'Consumer Discretionary', 'Housewares & Specialties', 'Sandy Springs, Georgia', '1989-04-30', '814453');
INSERT INTO `securities` VALUES ('324', 'NFX', 'Newfield Exploration Co', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '2010-12-20', '912750');
INSERT INTO `securities` VALUES ('325', 'NEM', 'Newmont Mining Corp. (Hldg. Co.)', 'reports', 'Materials', 'Gold', 'Denver, Colorado', '1969-06-30', '1164727');
INSERT INTO `securities` VALUES ('326', 'NWSA', 'News Corp. Class A', 'reports', 'Consumer Discretionary', 'Publishing', 'New York, New York', '2013-08-01', '1564708');
INSERT INTO `securities` VALUES ('327', 'NWS', 'News Corp. Class B', 'reports', 'Consumer Discretionary', 'Publishing', 'New York, New York', '2015-09-18', '1564708');
INSERT INTO `securities` VALUES ('328', 'NEE', 'NextEra Energy', 'reports', 'Utilities', 'MultiUtilities', 'Juno Beach, Florida', '1976-06-30', '753308');
INSERT INTO `securities` VALUES ('329', 'NLSN', 'Nielsen Holdings', 'reports', 'Industrials', 'Research & Consulting Services', 'New York, New York', '2013-07-09', '1492633');
INSERT INTO `securities` VALUES ('330', 'NKE', 'Nike', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Washington County, Oregon', '1988-11-30', '320187');
INSERT INTO `securities` VALUES ('331', 'NI', 'NiSource Inc.', 'reports', 'Utilities', 'MultiUtilities', 'Merrillville, Indiana', null, '1111711');
INSERT INTO `securities` VALUES ('332', 'NBL', 'Noble Energy Inc', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas', '2007-10-08', '72207');
INSERT INTO `securities` VALUES ('333', 'JWN', 'Nordstrom', 'reports', 'Consumer Discretionary', 'Department Stores', 'Seattle, Washington', '1986-08-31', '72333');
INSERT INTO `securities` VALUES ('334', 'NSC', 'Norfolk Southern Corp.', 'reports', 'Industrials', 'Railroads', 'Norfolk, Virginia', null, '702165');
INSERT INTO `securities` VALUES ('335', 'NTRS', 'Northern Trust Corp.', 'reports', 'Financials', 'Asset Management & Custody Banks', 'Chicago, Illinois', null, '73124');
INSERT INTO `securities` VALUES ('336', 'NOC', 'Northrop Grumman Corp.', 'reports', 'Industrials', 'Aerospace & Defense', 'West Falls Church, Virginia', '1985-06-30', '1133421');
INSERT INTO `securities` VALUES ('337', 'NRG', 'NRG Energy', 'reports', 'Utilities', 'Independent Power Producers & Energy Traders', 'Princeton, New Jersey', '2010-01-29', '1013871');
INSERT INTO `securities` VALUES ('338', 'NUE', 'Nucor Corp.', 'reports', 'Materials', 'Steel', 'Charlotte, North Carolina', '1985-04-30', '73309');
INSERT INTO `securities` VALUES ('339', 'NVDA', 'Nvidia Corporation', 'reports', 'Information Technology', 'Semiconductors', 'Santa Clara, California', null, '1045810');
INSERT INTO `securities` VALUES ('340', 'ORLY', 'O\'Reilly Automotive', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Springfield, Missouri', '2009-03-27', '898173');
INSERT INTO `securities` VALUES ('341', 'OXY', 'Occidental Petroleum', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Los Angeles, California', '1982-12-31', '797468');
INSERT INTO `securities` VALUES ('342', 'OMC', 'Omnicom Group', 'reports', 'Consumer Discretionary', 'Advertising', 'New York, New York', null, '29989');
INSERT INTO `securities` VALUES ('343', 'OKE', 'ONEOK', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Tulsa, Oklahoma', '2010-03-15', '1039684');
INSERT INTO `securities` VALUES ('344', 'ORCL', 'Oracle Corp.', 'reports', 'Information Technology', 'Application Software', 'Redwood Shores, California', '1989-08-31', '1341439');
INSERT INTO `securities` VALUES ('345', 'PCAR', 'PACCAR Inc.', 'reports', 'Industrials', 'Construction & Farm Machinery & Heavy Trucks', 'Bellevue, Washington', '1980-12-31', '75362');
INSERT INTO `securities` VALUES ('346', 'PH', 'Parker-Hannifin', 'reports', 'Industrials', 'Industrial Conglomerates', 'Cleveland, Ohio', '1985-11-30', '76334');
INSERT INTO `securities` VALUES ('347', 'PDCO', 'Patterson Companies', 'reports', 'Health Care', 'Health Care Supplies', 'St. Paul, Minnesota', null, '891024');
INSERT INTO `securities` VALUES ('348', 'PAYX', 'Paychex Inc.', 'reports', 'Information Technology', 'Internet Software & Services', 'Penfield, New York', null, '723531');
INSERT INTO `securities` VALUES ('349', 'PYPL', 'PayPal', 'reports', 'Information Technology', 'Data Processing & Outsourced Services', 'San Jose, California', '2015-07-20', '1633917');
INSERT INTO `securities` VALUES ('350', 'PNR', 'Pentair Ltd.', 'reports', 'Industrials', 'Industrial Machinery', 'Worsley, UK', '2012-10-01', '77360');
INSERT INTO `securities` VALUES ('351', 'PBCT', 'People\'s United Financial', 'reports', 'Financials', 'Thrifts & Mortgage Finance', 'Bridgeport, Connecticut', '2008-11-13', '1378946');
INSERT INTO `securities` VALUES ('352', 'PEP', 'PepsiCo Inc.', 'reports', 'Consumer Staples', 'Soft Drinks', 'Purchase, New York', null, '77476');
INSERT INTO `securities` VALUES ('353', 'PKI', 'PerkinElmer', 'reports', 'Health Care', 'Health Care Equipment', 'Waltham, Massachusetts', '1985-05-31', '31791');
INSERT INTO `securities` VALUES ('354', 'PRGO', 'Perrigo', 'reports', 'Health Care', 'Pharmaceuticals', 'Dublin, Ireland', '2011-12-19', '1585364');
INSERT INTO `securities` VALUES ('355', 'PFE', 'Pfizer Inc.', 'reports', 'Health Care', 'Pharmaceuticals', 'New York, New York', null, '78003');
INSERT INTO `securities` VALUES ('356', 'PCG', 'PG&E Corp.', 'reports', 'Utilities', 'MultiUtilities', 'San Francisco, California', null, '1004980');
INSERT INTO `securities` VALUES ('357', 'PM', 'Philip Morris International', 'reports', 'Consumer Staples', 'Tobacco', 'New York, New York', '2008-03-31', '1413329');
INSERT INTO `securities` VALUES ('358', 'PSX', 'Phillips 66', 'reports', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'Houston, Texas', '2012-05-01', '1534701');
INSERT INTO `securities` VALUES ('359', 'PNW', 'Pinnacle West Capital', 'reports', 'Utilities', 'MultiUtilities', 'Phoenix, Arizona', null, '764622');
INSERT INTO `securities` VALUES ('360', 'PXD', 'Pioneer Natural Resources', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Irving, Texas', '2008-09-24', '1038357');
INSERT INTO `securities` VALUES ('361', 'PBI', 'Pitney-Bowes', 'reports', 'Industrials', 'Technology, Hardware, Software and Supplies', 'Stamford, Connecticut', null, '78814');
INSERT INTO `securities` VALUES ('362', 'PNC', 'PNC Financial Services', 'reports', 'Financials', 'Banks', 'Pittsburgh, Pennsylvania', '1988-04-30', '713676');
INSERT INTO `securities` VALUES ('363', 'RL', 'Polo Ralph Lauren Corp.', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York, New York', '2007-02-02', '1037038');
INSERT INTO `securities` VALUES ('364', 'PPG', 'PPG Industries', 'reports', 'Materials', 'Diversified Chemicals', 'Pittsburgh, Pennsylvania', null, '79879');
INSERT INTO `securities` VALUES ('365', 'PPL', 'PPL Corp.', 'reports', 'Utilities', 'Electric Utilities', 'Allentown, Pennsylvania', null, '922224');
INSERT INTO `securities` VALUES ('366', 'PX', 'Praxair Inc.', 'reports', 'Materials', 'Industrial Gases', 'Danbury, Connecticut', '1992-07-01', '884905');
INSERT INTO `securities` VALUES ('367', 'PCLN', 'Priceline.com Inc', 'reports', 'Consumer Discretionary', 'Internet & Direct Marketing Retail', 'Norwalk, Connecticut', '2009-11-06', '1075531');
INSERT INTO `securities` VALUES ('368', 'PFG', 'Principal Financial Group', 'reports', 'Financials', 'Diversified Financial Services', 'Des Moines, Iowa', null, '1126328');
INSERT INTO `securities` VALUES ('369', 'PG', 'Procter & Gamble', 'reports', 'Consumer Staples', 'Personal Products', 'Cincinnati, Ohio', null, '80424');
INSERT INTO `securities` VALUES ('370', 'PGR', 'Progressive Corp.', 'reports', 'Financials', 'Property & Casualty Insurance', 'Mayfield Village, Ohio', null, '80661');
INSERT INTO `securities` VALUES ('371', 'PLD', 'Prologis', 'reports', 'Real Estate', 'REITs', 'San Francisco, California', null, '1045609');
INSERT INTO `securities` VALUES ('372', 'PRU', 'Prudential Financial', 'reports', 'Financials', 'Diversified Financial Services', 'Newark, New Jersey', null, '1137774');
INSERT INTO `securities` VALUES ('373', 'PEG', 'Public Serv. Enterprise Inc.', 'reports', 'Utilities', 'Electric Utilities', 'Newark, New Jersey', null, '788784');
INSERT INTO `securities` VALUES ('374', 'PSA', 'Public Storage', 'reports', 'Real Estate', 'REITs', 'Glendale, California', null, '1393311');
INSERT INTO `securities` VALUES ('375', 'PHM', 'Pulte Homes Inc.', 'reports', 'Consumer Discretionary', 'Homebuilding', 'Atlanta, Georgia', '1984-04-30', '822416');
INSERT INTO `securities` VALUES ('376', 'PVH', 'PVH Corp.', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York, New York', '2013-02-15', '78239');
INSERT INTO `securities` VALUES ('377', 'QRVO', 'Qorvo', 'reports', 'Information Technology', 'Semiconductors', 'Greensboro, North Carolina', '2015-06-11', '1604778');
INSERT INTO `securities` VALUES ('378', 'QCOM', 'QUALCOMM Inc.', 'reports', 'Information Technology', 'Semiconductors', 'San Diego, California', null, '804328');
INSERT INTO `securities` VALUES ('379', 'PWR', 'Quanta Services Inc.', 'reports', 'Industrials', 'Industrial Conglomerates', 'Houston, Texas', '2009-07-01', '1050915');
INSERT INTO `securities` VALUES ('380', 'DGX', 'Quest Diagnostics', 'reports', 'Health Care', 'Health Care Facilities', 'Madison, New Jersey', null, '1022079');
INSERT INTO `securities` VALUES ('381', 'RRC', 'Range Resources Corp.', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Fort Worth, Texas', '2007-12-21', '315852');
INSERT INTO `securities` VALUES ('382', 'RTN', 'Raytheon Co.', 'reports', 'Industrials', 'Aerospace & Defense', 'Waltham, Massachusetts', null, '1047122');
INSERT INTO `securities` VALUES ('383', 'O', 'Realty Income Corporation', 'reports', 'Real Estate', 'Retail REITs', 'San Diego, California', '2015-04-07', '726728');
INSERT INTO `securities` VALUES ('384', 'RHT', 'Red Hat Inc.', 'reports', 'Information Technology', 'Systems Software', 'Raleigh, North Carolina', '2009-07-27', '1087423');
INSERT INTO `securities` VALUES ('385', 'REGN', 'Regeneron', 'reports', 'Health Care', 'Biotechnology', 'Tarrytown, New York', '2013-05-01', '872589');
INSERT INTO `securities` VALUES ('386', 'RF', 'Regions Financial Corp.', 'reports', 'Financials', 'Diversified Financial Services', 'Birmingham, Alabama', null, '1281761');
INSERT INTO `securities` VALUES ('387', 'RSG', 'Republic Services Inc', 'reports', 'Industrials', 'Industrial Conglomerates', 'Phoenix, Arizona', '2008-12-05', '1060391');
INSERT INTO `securities` VALUES ('388', 'RAI', 'Reynolds American Inc.', 'reports', 'Consumer Staples', 'Tobacco', 'Winston-Salem, North Carolina', null, '1275283');
INSERT INTO `securities` VALUES ('389', 'RHI', 'Robert Half International', 'reports', 'Industrials', 'Human Resource & Employment Services', 'Menlo Park, California', null, '315213');
INSERT INTO `securities` VALUES ('390', 'ROK', 'Rockwell Automation Inc.', 'reports', 'Industrials', 'Industrial Conglomerates', 'Milwaukee, Wisconsin', null, '1024478');
INSERT INTO `securities` VALUES ('391', 'COL', 'Rockwell Collins', 'reports', 'Industrials', 'Industrial Conglomerates', 'Cedar Rapids, Iowa', null, '1137411');
INSERT INTO `securities` VALUES ('392', 'ROP', 'Roper Industries', 'reports', 'Industrials', 'Industrial Conglomerates', 'Sarasota, Florida', '2009-12-23', '882835');
INSERT INTO `securities` VALUES ('393', 'ROST', 'Ross Stores', 'reports', 'Consumer Discretionary', 'Apparel Retail', 'Pleasanton, California', '2009-12-21', '745732');
INSERT INTO `securities` VALUES ('394', 'RCL', 'Royal Caribbean Cruises Ltd', 'reports', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Miami, Florida', '2014-12-05', '884887');
INSERT INTO `securities` VALUES ('395', 'R', 'Ryder System', 'reports', 'Industrials', 'Industrial Conglomerates', 'Miami, Florida', '1982-12-31', '85961');
INSERT INTO `securities` VALUES ('396', 'SPGI', 'S&P Global, Inc.', 'reports', 'Financials', 'Diversified Financial Services', 'New York, New York', null, '64040');
INSERT INTO `securities` VALUES ('397', 'CRM', 'Salesforce.com', 'reports', 'Information Technology', 'Internet Software & Services', 'San Francisco, California', '2008-09-15', '1108524');
INSERT INTO `securities` VALUES ('398', 'SCG', 'SCANA Corp', 'reports', 'Utilities', 'MultiUtilities', 'Cayce, South Carolina', '2009-01-02', '754737');
INSERT INTO `securities` VALUES ('399', 'SLB', 'Schlumberger Ltd.', 'reports', 'Energy', 'Oil & Gas Equipment & Services', 'Curaçao, Kingdom of the Netherlands', '1965-03-31', '87347');
INSERT INTO `securities` VALUES ('400', 'SNI', 'Scripps Networks Interactive Inc.', 'reports', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'Cincinnati, Ohio', '2008-07-01', '1430602');
INSERT INTO `securities` VALUES ('401', 'STX', 'Seagate Technology', 'reports', 'Information Technology', 'Computer Storage & Peripherals', 'Dublin, Ireland', '2012-07-02', '1137789');
INSERT INTO `securities` VALUES ('402', 'SEE', 'Sealed Air', 'reports', 'Materials', 'Paper Packaging', 'Elmwood Park, New Jersey', null, '1012100');
INSERT INTO `securities` VALUES ('403', 'SRE', 'Sempra Energy', 'reports', 'Utilities', 'MultiUtilities', 'San Diego, California', null, '1032208');
INSERT INTO `securities` VALUES ('404', 'SHW', 'Sherwin-Williams', 'reports', 'Materials', 'Specialty Chemicals', 'Cleveland, Ohio', '1964-06-30', '89800');
INSERT INTO `securities` VALUES ('405', 'SIG', 'Signet Jewelers', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Hamilton, Bermuda', '2015-07-29', '832988');
INSERT INTO `securities` VALUES ('406', 'SPG', 'Simon Property Group Inc', 'reports', 'Real Estate', 'REITs', 'Indianapolis, Indiana', null, '1063761');
INSERT INTO `securities` VALUES ('407', 'SWKS', 'Skyworks Solutions', 'reports', 'Information Technology', 'Semiconductors', 'Woburn, Massachusetts', '2015-03-12', '4127');
INSERT INTO `securities` VALUES ('408', 'SLG', 'SL Green Realty', 'reports', 'Real Estate', 'Office REITs', 'New York, New York', '2015-03-20', '1040971');
INSERT INTO `securities` VALUES ('409', 'SNA', 'Snap-On Inc.', 'reports', 'Consumer Discretionary', 'Household Appliances', 'Kenosha, Wisconsin', '1982-09-30', '91440');
INSERT INTO `securities` VALUES ('410', 'SO', 'Southern Co.', 'reports', 'Utilities', 'Electric Utilities', 'Atlanta, Georgia', null, '92122');
INSERT INTO `securities` VALUES ('411', 'LUV', 'Southwest Airlines', 'reports', 'Industrials', 'Airlines', 'Dallas, Texas', '1994-07-01', '92380');
INSERT INTO `securities` VALUES ('412', 'SWN', 'Southwestern Energy', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Houston, Texas[6]', '2008-06-06', '7332');
INSERT INTO `securities` VALUES ('413', 'SE', 'Spectra Energy Corp.', 'reports', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'Houston, Texas', null, '1373835');
INSERT INTO `securities` VALUES ('414', 'SWK', 'Stanley Black & Decker', 'reports', 'Consumer Discretionary', 'Household Appliances', 'New Britain, Connecticut', '1982-09-30', '93556');
INSERT INTO `securities` VALUES ('415', 'SPLS', 'Staples Inc.', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Framingham, Massachusetts', null, '791519');
INSERT INTO `securities` VALUES ('416', 'SBUX', 'Starbucks Corp.', 'reports', 'Consumer Discretionary', 'Restaurants', 'Seattle, Washington', null, '829224');
INSERT INTO `securities` VALUES ('417', 'STT', 'State Street Corp.', 'reports', 'Financials', 'Diversified Financial Services', 'Boston, Massachusetts', null, '93751');
INSERT INTO `securities` VALUES ('418', 'SRCL', 'Stericycle Inc', 'reports', 'Industrials', 'Industrial Conglomerates', 'Lake Forest, Illinois', '2008-11-19', '861878');
INSERT INTO `securities` VALUES ('419', 'SYK', 'Stryker Corp.', 'reports', 'Health Care', 'Health Care Equipment', 'Kalamazoo, Michigan', null, '310764');
INSERT INTO `securities` VALUES ('420', 'STI', 'SunTrust Banks', 'reports', 'Financials', 'Banks', 'Atlanta, Georgia', '1988-05-31', '750556');
INSERT INTO `securities` VALUES ('421', 'SYMC', 'Symantec Corp.', 'reports', 'Information Technology', 'Application Software', 'Mountain View, California', '2003-03-25', '849399');
INSERT INTO `securities` VALUES ('422', 'SYF', 'Synchrony Financial', 'reports', 'Financials', 'Consumer Finance', 'Stamford, Connecticut', '2015-11-18', '1601712');
INSERT INTO `securities` VALUES ('423', 'SYY', 'Sysco Corp.', 'reports', 'Consumer Staples', 'Food Distributors', 'Houston, Texas', '1986-12-31', '96021');
INSERT INTO `securities` VALUES ('424', 'TROW', 'T. Rowe Price Group', 'reports', 'Financials', 'Diversified Financial Services', 'Baltimore, Maryland', null, '1113169');
INSERT INTO `securities` VALUES ('425', 'TGT', 'Target Corp.', 'reports', 'Consumer Discretionary', 'General Merchandise Stores', 'Minneapolis, Minnesota', '1976-12-31', '27419');
INSERT INTO `securities` VALUES ('426', 'TEL', 'TE Connectivity Ltd.', 'reports', 'Information Technology', 'Electronic Manufacturing Services', 'Schaffhausen, Switzerland', '2011-10-17', '1385157');
INSERT INTO `securities` VALUES ('427', 'TGNA', 'Tegna, Inc.', 'reports', 'Consumer Discretionary', 'Publishing', 'McLean, Virginia', '1975-12-31', '39899');
INSERT INTO `securities` VALUES ('428', 'TDC', 'Teradata Corp.', 'reports', 'Information Technology', 'Application Software', 'Miamisburg, Ohio', '2007-10-01', '816761');
INSERT INTO `securities` VALUES ('429', 'TSO', 'Tesoro Petroleum Co.', 'reports', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'San Antonio, Texas', '2007-09-27', '50104');
INSERT INTO `securities` VALUES ('430', 'TXN', 'Texas Instruments', 'reports', 'Information Technology', 'Semiconductors', 'Dallas, Texas', null, '97476');
INSERT INTO `securities` VALUES ('431', 'TXT', 'Textron Inc.', 'reports', 'Industrials', 'Industrial Conglomerates', 'Providence, Rhode Island', '1978-12-31', '217346');
INSERT INTO `securities` VALUES ('432', 'BK', 'The Bank of New York Mellon Corp.', 'reports', 'Financials', 'Banks', 'New York, New York', null, '1390777');
INSERT INTO `securities` VALUES ('433', 'CLX', 'The Clorox Company', 'reports', 'Consumer Staples', 'Household Products', 'Oakland, California', '1969-03-31', '21076');
INSERT INTO `securities` VALUES ('434', 'COO', 'The Cooper Companies', 'reports', 'Health Care', 'Health Care Supplies', 'Pleasanton, California', '2016-09-23', '711404');
INSERT INTO `securities` VALUES ('435', 'HSY', 'The Hershey Company', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Hershey, Pennsylvania', null, '47111');
INSERT INTO `securities` VALUES ('436', 'MOS', 'The Mosaic Company', 'reports', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Plymouth, Minnesota', '2011-09-26', '1285785');
INSERT INTO `securities` VALUES ('437', 'TRV', 'The Travelers Companies Inc.', 'reports', 'Financials', 'Property & Casualty Insurance', 'New York, New York', null, '86312');
INSERT INTO `securities` VALUES ('438', 'DIS', 'The Walt Disney Company', 'reports', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'Burbank, California', '1976-06-30', '1001039');
INSERT INTO `securities` VALUES ('439', 'TMO', 'Thermo Fisher Scientific', 'reports', 'Health Care', 'Health Care Equipment', 'Waltham, Massachusetts', null, '97745');
INSERT INTO `securities` VALUES ('440', 'TIF', 'Tiffany & Co.', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York, New York', null, '98246');
INSERT INTO `securities` VALUES ('441', 'TWX', 'Time Warner Inc.', 'reports', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'New York, New York', null, '1105705');
INSERT INTO `securities` VALUES ('442', 'TJX', 'TJX Companies Inc.', 'reports', 'Consumer Discretionary', 'Apparel Retail', 'Framingham, Massachusetts', '1985-09-30', '109198');
INSERT INTO `securities` VALUES ('443', 'TMK', 'Torchmark Corp.', 'reports', 'Financials', 'Life & Health Insurance', 'McKinney, Texas', '1989-04-30', '320335');
INSERT INTO `securities` VALUES ('444', 'TSS', 'Total System Services', 'reports', 'Information Technology', 'Internet Software & Services', 'Columbus, Georgia', '2008-01-02', '721683');
INSERT INTO `securities` VALUES ('445', 'TSCO', 'Tractor Supply Company', 'reports', 'Consumer Discretionary', 'Specialty Retail', 'Brentwood, Tennessee', '2014-01-24', '916365');
INSERT INTO `securities` VALUES ('446', 'TDG', 'TransDigm Group', 'reports', 'Industrials', 'Aerospace & Defense', 'Cleveland, Ohio', '2016-06-03', '1260221');
INSERT INTO `securities` VALUES ('447', 'RIG', 'Transocean', 'reports', 'Energy', 'Oil & Gas Drilling', 'Vernier, Switzerland', '2013-10-29', '1451505');
INSERT INTO `securities` VALUES ('448', 'TRIP', 'TripAdvisor', 'reports', 'Consumer Discretionary', 'Internet & Direct Marketing Retail', 'Newton, Massachusetts', '2011-12-21', '1526520');
INSERT INTO `securities` VALUES ('449', 'FOXA', 'Twenty-First Century Fox Class A', 'reports', 'Consumer Discretionary', 'Publishing', 'New York, New York', '2013-07-01', '1308161');
INSERT INTO `securities` VALUES ('450', 'FOX', 'Twenty-First Century Fox Class B', 'reports', 'Consumer Discretionary', 'Publishing', 'New York, New York', '2015-09-18', '1308161');
INSERT INTO `securities` VALUES ('451', 'TSN', 'Tyson Foods', 'reports', 'Consumer Staples', 'Packaged Foods & Meats', 'Springdale, Arkansas', null, '100493');
INSERT INTO `securities` VALUES ('452', 'USB', 'U.S. Bancorp', 'reports', 'Financials', 'Banks', 'Minneapolis, Minnesota', null, '36104');
INSERT INTO `securities` VALUES ('453', 'UDR', 'UDR Inc', 'reports', 'Real Estate', 'Residential REITs', 'Highlands Ranch, Colorado', '2016-03-07', '74208');
INSERT INTO `securities` VALUES ('454', 'ULTA', 'Ulta Salon Cosmetics & Fragrance Inc', 'reports', 'Consumer Discretionary', 'Specialty Stores', 'Bolingbrook, Illinois', '2016-04-18', '1403568');
INSERT INTO `securities` VALUES ('455', 'UA', 'Under Armour', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Baltimore, Maryland', '2014-05-01', '1336917');
INSERT INTO `securities` VALUES ('456', 'UAA', 'Under Armour', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Baltimore, Maryland', '2016-03-25', '1336917');
INSERT INTO `securities` VALUES ('457', 'UNP', 'Union Pacific', 'reports', 'Industrials', 'Railroads', 'Omaha, Nebraska', null, '100885');
INSERT INTO `securities` VALUES ('458', 'UAL', 'United Continental Holdings', 'reports', 'Industrials', 'Airlines', 'Chicago, Illinois', '2015-09-03', '100517');
INSERT INTO `securities` VALUES ('459', 'UNH', 'United Health Group Inc.', 'reports', 'Health Care', 'Managed Health Care', 'Minnetonka, Minnesota', '1994-07-01', '731766');
INSERT INTO `securities` VALUES ('460', 'UPS', 'United Parcel Service', 'reports', 'Industrials', 'Air Freight & Logistics', 'Atlanta, Georgia', null, '1090727');
INSERT INTO `securities` VALUES ('461', 'URI', 'United Rentals, Inc.', 'reports', 'Industrials', 'Trading Companies & Distributors', 'Stamford, Connecticut', '2014-09-20', '1067701');
INSERT INTO `securities` VALUES ('462', 'UTX', 'United Technologies', 'reports', 'Industrials', 'Industrial Conglomerates', 'Hartford, Connecticut', null, '101829');
INSERT INTO `securities` VALUES ('463', 'UHS', 'Universal Health Services, Inc.', 'reports', 'Health Care', 'Health Care Facilities', 'King of Prussia, Pennsylvania', '2014-09-20', '352915');
INSERT INTO `securities` VALUES ('464', 'UNM', 'Unum Group', 'reports', 'Financials', 'Diversified Financial Services', 'Chattanooga, Tennessee', '1994-03-01', '5513');
INSERT INTO `securities` VALUES ('465', 'URBN', 'Urban Outfitters', 'reports', 'Consumer Discretionary', 'Apparel Retail', 'Philadelphia, Pennsylvania', '2010-02-08', '912615');
INSERT INTO `securities` VALUES ('466', 'VFC', 'V.F. Corp.', 'reports', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Greensboro, North Carolina', '1979-06-30', '103379');
INSERT INTO `securities` VALUES ('467', 'VLO', 'Valero Energy', 'reports', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'San Antonio, Texas', null, '1035002');
INSERT INTO `securities` VALUES ('468', 'VAR', 'Varian Medical Systems', 'reports', 'Health Care', 'Health Care Equipment', 'Palo Alto, California', '2007-02-12', '203527');
INSERT INTO `securities` VALUES ('469', 'VTR', 'Ventas Inc', 'reports', 'Real Estate', 'REITs', 'Chicago, Illinois', '2009-03-04', '740260');
INSERT INTO `securities` VALUES ('470', 'VRSN', 'Verisign Inc.', 'reports', 'Information Technology', 'Internet Software & Services', 'Dulles, Virginia', null, '1014473');
INSERT INTO `securities` VALUES ('471', 'VRSK', 'Verisk Analytics', 'reports', 'Industrials', 'Research & Consulting Services', 'Jersey City, New Jersey', '2015-10-08', '1442145');
INSERT INTO `securities` VALUES ('472', 'VZ', 'Verizon Communications', 'reports', 'Telecommunications Services', 'Integrated Telecommunications Services', 'New York, New York', '1983-11-30', '732712');
INSERT INTO `securities` VALUES ('473', 'VRTX', 'Vertex Pharmaceuticals Inc', 'reports', 'Health Care', 'Biotechnology', 'Cambridge, Massachusetts', '2013-09-23', '875320');
INSERT INTO `securities` VALUES ('474', 'VIAB', 'Viacom Inc.', 'reports', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'New York, New York', null, '1339947');
INSERT INTO `securities` VALUES ('475', 'V', 'Visa Inc.', 'reports', 'Information Technology', 'Internet Software & Services', 'San Francisco, California', '2009-12-21', '1403161');
INSERT INTO `securities` VALUES ('476', 'VNO', 'Vornado Realty Trust', 'reports', 'Real Estate', 'REITs', 'New York, New York', null, '899689');
INSERT INTO `securities` VALUES ('477', 'VMC', 'Vulcan Materials', 'reports', 'Materials', 'Construction Materials', 'Birmingham, Alabama', null, '1396009');
INSERT INTO `securities` VALUES ('478', 'WMT', 'Wal-Mart Stores', 'reports', 'Consumer Staples', 'Hypermarkets & Super Centers', 'Bentonville, Arkansas', '1982-08-31', '104169');
INSERT INTO `securities` VALUES ('479', 'WBA', 'Walgreens Boots Alliance', 'reports', 'Consumer Staples', 'Drug Retail', 'Deerfield, Illinois', '1979-12-31', '1618921');
INSERT INTO `securities` VALUES ('480', 'WM', 'Waste Management Inc.', 'reports', 'Industrials', 'Environmental Services', 'Houston, Texas', null, '823768');
INSERT INTO `securities` VALUES ('481', 'WAT', 'Waters Corporation', 'reports', 'Health Care', 'Health Care Distributors', 'Milford, Massachusetts', null, '1000697');
INSERT INTO `securities` VALUES ('482', 'WEC', 'Wec Energy Group Inc', 'reports', 'Utilities', 'Electric Utilities', 'Milwaukee, Wisconsin', '2008-10-31', '783325');
INSERT INTO `securities` VALUES ('483', 'WFC', 'Wells Fargo', 'reports', 'Financials', 'Banks', 'San Francisco, California', '1976-06-30', '72971');
INSERT INTO `securities` VALUES ('484', 'HCN', 'Welltower Inc.', 'reports', 'Real Estate', 'REITs', 'Toledo, Ohio', '2009-01-30', '766704');
INSERT INTO `securities` VALUES ('485', 'WDC', 'Western Digital', 'reports', 'Information Technology', 'Computer Storage & Peripherals', 'Irvine, California', '2009-07-01', '106040');
INSERT INTO `securities` VALUES ('486', 'WU', 'Western Union Co', 'reports', 'Information Technology', 'Internet Software & Services', 'Englewood, Colorado', null, '1365135');
INSERT INTO `securities` VALUES ('487', 'WRK', 'WestRock Company', 'reports', 'Materials', 'Paper Packaging', 'Richmond, Virginia', null, '1636023');
INSERT INTO `securities` VALUES ('488', 'WY', 'Weyerhaeuser Corp.', 'reports', 'Real Estate', 'REITs', 'Federal Way, Washington', null, '106535');
INSERT INTO `securities` VALUES ('489', 'WHR', 'Whirlpool Corp.', 'reports', 'Consumer Discretionary', 'Household Appliances', 'Benton Harbor, Michigan', null, '106640');
INSERT INTO `securities` VALUES ('490', 'WFM', 'Whole Foods Market', 'reports', 'Consumer Staples', 'Food Retail', 'Austin, Texas', null, '865436');
INSERT INTO `securities` VALUES ('491', 'WMB', 'Williams Cos.', 'reports', 'Energy', 'Oil & Gas Exploration & Production', 'Tulsa, Oklahoma', '1975-03-31', '107263');
INSERT INTO `securities` VALUES ('492', 'WLTW', 'Willis Towers Watson', 'reports', 'Financials', 'Insurance Brokers', 'London, United Kingdom', '2016-01-05', '1140536');
INSERT INTO `securities` VALUES ('493', 'WYN', 'Wyndham Worldwide', 'reports', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Parsippany, New Jersey', null, '1361658');
INSERT INTO `securities` VALUES ('494', 'WYNN', 'Wynn Resorts Ltd', 'reports', 'Consumer Discretionary', 'Casinos & Gaming', 'Las Vegas, Nevada', '2008-11-14', '1174922');
INSERT INTO `securities` VALUES ('495', 'XEL', 'Xcel Energy Inc', 'reports', 'Utilities', 'MultiUtilities', 'Minneapolis, Minnesota', null, '72903');
INSERT INTO `securities` VALUES ('496', 'XRX', 'Xerox Corp.', 'reports', 'Information Technology', 'IT Consulting & Other Services', 'Norwalk, Connecticut', null, '108772');
INSERT INTO `securities` VALUES ('497', 'XLNX', 'Xilinx Inc', 'reports', 'Information Technology', 'Semiconductors', 'San Jose, California', null, '743988');
INSERT INTO `securities` VALUES ('498', 'XL', 'XL Capital', 'reports', 'Financials', 'Property & Casualty Insurance', 'Hamilton, Bermuda', null, '875159');
INSERT INTO `securities` VALUES ('499', 'XYL', 'Xylem Inc.', 'reports', 'Industrials', 'Industrial Conglomerates', 'White Plains, New York', '2011-11-01', '1524472');
INSERT INTO `securities` VALUES ('500', 'YHOO', 'Yahoo Inc.', 'reports', 'Information Technology', 'Internet Software & Services', 'Sunnyvale, California', null, '1011006');
INSERT INTO `securities` VALUES ('501', 'YUM', 'Yum! Brands Inc', 'reports', 'Consumer Discretionary', 'Restaurants', 'Louisville, Kentucky', '1997-10-06', '1041061');
INSERT INTO `securities` VALUES ('502', 'ZBH', 'Zimmer Biomet Holdings', 'reports', 'Health Care', 'Health Care Equipment', 'Warsaw, Indiana', null, '1136869');
INSERT INTO `securities` VALUES ('503', 'ZION', 'Zions Bancorp', 'reports', 'Financials', 'Regional Banks', 'Salt Lake City, Utah', null, '109380');
INSERT INTO `securities` VALUES ('504', 'ZTS', 'Zoetis', 'reports', 'Health Care', 'Pharmaceuticals', 'Florham Park, New Jersey', '2013-06-21', '1555280');
